# Name
name: PTBOT-CICD

# Trigger
on: push

#Job
jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
#Git checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

#Build & Push
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: make image

      - name: Push image
        run: make push  