# Name
name: PTBOT-CICD

# 
on: push
# 
jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
# 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
# 
      - name: Make build
        run: make build